### ISSUE TITLE
Dropwizard 0.7 support

### ISSUE THREAD

**Issue by RobertButera** [Multifarious/dw-shiro-bundle#1]
Hi,

Was wondering if this would be updated any time soon to be compatible with DropWizard 0,7?

Rob

**Comment by prb** [comment]
We'll update this shortly, as we're migrating a few of our existing DW 0.6.2 apps to 0.7.0.

**Comment by prb** [comment]
Update completed, thanks to @jalkanen.  Release v1 pushed up to Maven Central.
